# Generated by Django 6.0.5 on 2026-05-27 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca_virtual', '0001_initial'),
    ]

    operations = [
    ]
